include:
  - board: xiao_ble
    shield: totem_left rgbled_adapter
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: totem_right rgbled_adapter
    snippet: zmk-usb-logging
# there is no settingsreset (needed) for the XIAO
